FROM ubuntu:18.04
LABEL maintainer="Ivan Buetler <ivan.buetler@hacking-lab.com>"

ENV DEBIAN_FRONTEND=noninteractive

# Add s6-overlay
ENV S6_OVERLAY_VERSION=v3.1.5.0

RUN apt update && apt install -y dnsutils adduser passwd curl bash net-tools openssl pwgen vim xz-utils && \ 
	apt clean && \
	apt autoremove

RUN curl -sSL https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz | tar -Jxpf - -C / 
RUN curl -sSL https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-i686.tar.xz | tar -Jxpf - -C / 


ADD root /

ENTRYPOINT ["/init"]
CMD []


